language: generic

sudo: required

services:
  - docker

script:
  - docker build -t cbsan/php:5.6 .

after_success:
  - docker login -u="$DOCKER_USER" -p="$DOCKER_PASS" -e="$DOCKER_EMAIL";
  - docker push cbsan/php:5.6;
  