language: bash

sudo: required

services:
  - docker

install:
  - git clone --depth=50 --branch=master https://github.com/cbsan/docker-php.git cbsan/docker-php

script:
  - docker build -t cbsan/php:5.6-sybase16 .

after_success:
  - docker login -u="$DOCKER_USER" -p="$DOCKER_PASS" -e="$DOCKER_EMAIL"
  - docker push cbsan/php:5.6-sybase16
  
