language: ruby

sudo: required

services:
    - docker

env:
    - VERSION=5.6

install:
    - git clone --depth=50 --branch=php${VERSION} https://github.com/cbsan/docker-php.git cbsan/docker-php

script:
    - docker build -t cbsan/php:${VERSION} .

after_success:
    - docker login -u="$DOCKER_USER" -p="$DOCKER_PASS" -e="$DOCKER_EMAIL"
    - docker push cbsan/php:${VERSION}